kata-containers/cgroups-rs

src/blkio.rs
src/cgroup.rs
src/cgroup_builder.rs
src/cpu.rs
src/cpuacct.rs
src/cpuset.rs
src/devices.rs
src/error.rs
src/freezer.rs
src/hierarchies.rs
src/hugetlb.rs
src/lib.rs
src/memory.rs
src/net_cls.rs
src/net_prio.rs
src/perf_event.rs
src/pid.rs
src/rdma.rs
tests/builder.rs
tests/cgroup.rs
tests/cpuset.rs
tests/devices.rs
tests/pids.rs
tools/create_cgroup.sh
tools/delete_cgroup.sh

Add SPDX-License-Identifier for all existing codes.
Fixes: #2

add SPDX-License-Identifier for all source

---

Cargo.toml
src/blkio.rs
src/cgroup.rs
src/cgroup_builder.rs
src/cpu.rs
src/cpuacct.rs
src/cpuset.rs
src/devices.rs
src/error.rs
src/events.rs
src/freezer.rs
src/hierarchies.rs
src/hugetlb.rs
src/lib.rs
src/memory.rs
src/net_cls.rs
src/net_prio.rs
src/pid.rs
src/rdma.rs
src/systemd.rs
tests/builder.rs
tests/cgroup.rs
tests/cpuset.rs
tests/devices.rs
tests/hugetlb.rs
tests/memory.rs
tests/pids.rs
tests/resources.rs

This PR adds basic cgroup v2 support for Kata containers 2.0
And will fix #1

add cgroup v2 support

---

src/cpu.rs
src/lib.rs
tests/cpu.rs

`cfs_quota` can be set to -1 to indicate no limit
Fixes: #5

cpu: change cfs_quota from u64 to i64

---

src/error.rs

Errors cause should be shared to let anyhow to wrap it.
Fixes: #7

errors: add sync marker to error cause

---

src/lib.rs

function  libc::rmdir with a  prototype: rmdir(path: *const c_char) -> c_int
and c_char is equal to i8 on x86, but it is equal to u8 on ARM arch,
so we need to use type c_char instead of i8 to avoid compiling error.
Fixes: #9
Signed-off-by: zhanghj <zhanghj.lc@inspur.com>

lib: fix compiling error for type i8 in aarch64 environment

---

.github/workflows/PR-wip-checks.yaml
.github/workflows/commit-message-check.yaml

Basic checks includes:
- Must have commit title/body
- Must have DCO(SoC)
- Title/Body line length are limited 75/72
- Add wip/do-not-merge to label PRs that could be merged

add basic GitHub workflow for basic checks

---

.travis.yml
src/blkio.rs
src/cgroup.rs
src/cgroup_builder.rs
src/cpu.rs
src/cpuacct.rs
src/cpuset.rs
src/devices.rs
src/error.rs
src/events.rs
src/freezer.rs
src/hierarchies.rs
src/hugetlb.rs
src/memory.rs
src/net_cls.rs
src/net_prio.rs
src/perf_event.rs
src/pid.rs
src/rdma.rs
src/systemd.rs

And in Travis CI, treat warnings as error
to keep from merging codes with warning.
Fixes: #13

fix build warnings

---

Cargo.toml
README.md
src/blkio.rs
src/cgroup.rs
src/cgroup_builder.rs
src/cpu.rs
src/cpuacct.rs
src/cpuset.rs
src/devices.rs
src/error.rs
src/freezer.rs
src/hierarchies.rs
src/hugetlb.rs
src/lib.rs
src/memory.rs
src/net_cls.rs
src/net_prio.rs
src/perf_event.rs
src/pid.rs
src/rdma.rs
src/systemd.rs
tests/builder.rs
tests/cgroup.rs
tests/cpu.rs
tests/cpuset.rs
tests/devices.rs
tests/hugetlb.rs
tests/memory.rs
tests/pids.rs
tests/resources.rs

- Refactor
- Use Option as resource fields, remove the update switch: update_values
- Make Cgroup can be stored in struct(remove lifetime, impl Clone, Default, Debug for Cgroup )
- New features
- Expose deletion error
- Support customized attributes for CpuController and MemController(for customized kernels)
- Detect subsystems and get root from /proc/self/mountinfo
- Support set notify_on_release & release_agent
- Fix bugs
- Update tests

Ready to release 0.2.0

---

src/blkio.rs
src/cpu.rs
src/cpuacct.rs
src/cpuset.rs
src/hugetlb.rs
src/lib.rs
src/memory.rs
src/net_cls.rs
src/net_prio.rs
src/pid.rs
src/rdma.rs

There's so many Duplicated read_string_from method in different subsystem's implementation, and so as read_u64_from/read_i64_from methods.
(1) Move the read_string_from method into `lib.rs`, called by each subsystem implementation as needed.
(2) Refactor read_u[i]64_from method with the help Rust Generic function `read_from` and wrapped by read_u64_from or read_i64_from.
fix: #20
Signed-off-by: LiYa'nan <oliverliyn@gmail.com>

optimize and refactor: read_to_string and read_i[u]64_from

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/enhancement-request.md
.github/ISSUE_TEMPLATE/feature_request.md

cgroups-rs should not use the repository default issue templates.
Let's add a private version to override the default ones.
Fixes: #29
Signed-off-by: Peng Tao <bergwolf@hyper.sh>

github: add issue templates

---

Cargo.toml

Display readme on the crate's page.
Signed-off-by: Tim Zhang <tim@hyper.sh>

Add field homepage and readme for Cargo.toml

---

Cargo.toml
src/hierarchies.rs

The procinfo library gets all the mount info,
but we don't need all the mount info.
Signed-off-by: quanweiZhou <quanweiZhou@linux.alibaba.com>

cgroup: get the mount info without procinfo

---

Cargo.toml
tests/pids.rs

to pull in https://github.com/nix-rust/nix/pull/1372 and get statfs MAGIC constants on s390x. Additionally, fork() calls in tests now have to be marked unsafe.
Fixes: #37
Signed-off-by: Jakob Naucke <jakob.naucke@ibm.com>

Update nix to 0.20.0

---

src/memory.rs

For older kernels, it is possible that there is no hierarchical numa
stats.
Fixes: #36

memory: fix panic when no hierarchical numa stat is available

---

src/hierarchies.rs

Clone is useful.
Signed-off-by: Tim Zhang <tim@hyper.sh>

Impl Clone for hierarchies:V1, hierarchies:V2

---

src/freezer.rs

When reading from the freezer file, it should trim it
first, and the string may container an '\n'.
Fixes: #48
Signed-off-by: fupan.lfp <fupan.lfp@antgroup.com>

freezer: fix the issue of missing trim the str

---

Cargo.toml
src/blkio.rs
src/cpu.rs
src/cpuacct.rs
src/cpuset.rs
src/devices.rs
src/freezer.rs
src/lib.rs
src/memory.rs

Add feature "serde" that derives all resource and statistics types from Serialize and Deserialize. The feature is turned off by default.
Fixes #54
Fixes #55
Fixes #56

Add Serialize/Deserialize to resource and stat types

---

.github/workflows/bvt.yaml
.github/workflows/commit-message-check.yaml

commit bf5af7b1951438e807ef5eebed01bc5161b7a866 (HEAD -> action-lock-rust-version, origin/action-lock-rust-version)
Author: Tim Zhang <tim@hyper.sh>
Date:   Wed Nov 10 19:30:12 2021 +0800
action: fix the the body line checker
the original regex can not handle pasted error message
rightly. this commit will fix this.
Signed-off-by: Tim Zhang <tim@hyper.sh>
commit 2e3719dbd5f0a31d55fabc68bc0b49843b71c076
Author: Tim Zhang <tim@hyper.sh>
Date:   Wed Nov 10 16:28:39 2021 +0800
action: Lock rust version to 1.52
Got the following error in the clippy:
error: this expression borrows a reference (`&str`) that is immediately dereferenced by the compiler
--> tests/cpuset.rs:54:37
|
54 |             let r = cpuset.set_cpus(&cpus);
|                                     ^^^^^ help: change this to: …

action: Lock rust version and fix commit-body checker

---

src/hierarchies.rs
src/lib.rs

Fixes #62
Signed-off-by: quanweiZhou <quanweiZhou@linux.alibaba.com>

fix: read task hang when the cgroup dir removed after open

---

src/hierarchies.rs

`FreezerController` implements the functionality for cgroups v2, but the freezer subsystem is not instantiated, because there is no "freezer" controller in `cgroup.controllers` (the functionality is supported via `cgroup.freeze`, which is not part of any controller).
This PR forces the "freezer" controller for cgroups v2.

fix: support FreezerController in cgroups v2

---

Cargo.toml
tests/cpuset.rs

Enforces use of a version of nix which contains a patch for
RUSTSEC-2021-0119.
Fixes #58
Signed-off-by: Jon Magnuson <jon.magnuson@gmail.com>

deps: update nix to 0.20.2

---

Cargo.toml

Update the `nix` crate to version `0.23.0` to resolve a dependency
issue related to making `cargo audit` run cleanly for the Kata
Containers agent.
See:
https://github.com/kata-containers/kata-containers/pull/3125
Fixes: #66.
Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

cargo: Update nix to latest version

---

src/cgroup.rs

support get cgroup relative paths by process pid
Signed-off-by: Zhang Tianyang <burning9699@gmail.com>

cgroup: support get cgroup relative paths by process pid

---

src/cpu.rs
src/events.rs
src/hierarchies.rs
src/lib.rs
src/systemd.rs
tests/builder.rs
tests/hugetlb.rs
tests/memory.rs

Fix clippy lints from clippy 0.1.60 (7737e0b 2022-04-04).

clippy: Fix clippy version 0.1.60

---

src/memory.rs
tests/builder.rs
tests/memory.rs

Setting (writing into) `memory.kmem.limit_in_bytes` is not supported in
Linux kernel >= 5.16 (see kernel commit 58056f77502: "memcg, kmem:
further deprecate kmem.limit_in_bytes"):
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=58056f77502
If the write call in `set_kmem_limit()` returns EOPNOTSUPP, log a
warning message but ignore the error (do nothing).
Add a unit-test for `set_kmem_limit` in cgroups v1.
Fix #81
Signed-off-by: Dov Murik <dov.murik1@il.ibm.com>

memory: set_kmem_limit: ignore Unsupported error

---

src/blkio.rs
src/lib.rs

Customized attributes are useful for customized kernels.
It's a new way to achieve the closed pr #85 's aim.
Signed-off-by: Tim Zhang <tim@hyper.sh>

blkio: Add support for customized-attributes

---

Cargo.toml
src/blkio.rs
src/cgroup.rs
src/cpu.rs
src/cpuacct.rs
src/cpuset.rs
src/devices.rs
src/error.rs
src/events.rs
src/freezer.rs
src/hugetlb.rs
src/lib.rs
src/memory.rs
src/net_cls.rs
src/net_prio.rs
src/pid.rs
src/rdma.rs
tests/cpuset.rs

For some cgroup file operations, when failed, add the path and the value (for write operation) to the error message.
Fixes: #93
Signed-off-by: bin liu <liubin0329@gmail.com>

error: introduce thiserror to add path to error message

---

src/cgroup.rs
src/cgroup_builder.rs
src/error.rs
src/hierarchies.rs
src/lib.rs
tests/builder.rs
tests/cgroup.rs
tests/cpu.rs
tests/cpuset.rs
tests/devices.rs
tests/hugetlb.rs
tests/memory.rs
tests/pids.rs
tests/resources.rs

Support to set threaded mode in cgroup v2. The premise of switching to threaded mode is that only the cgroup of cpuset, cpu and pids is supported.
Fixes: #90
Signed-off-by: yaoyinnan <yaoyinnan@foxmail.com>

cgroup: support to set threaded mode in cgroup v2

---

src/error.rs

cause method for std::error::Error is depricated by rust, source method is recommended.
Fixes: #107
Signed-off-by: Jianyong Wu <jianyong.wu@arm.com>

error: replace cause method with source

---

src/lib.rs

nanoseconds -> microseonds
Noticed while debugging, also fits Red Hat documentation https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/resource_management_guide/sec-cpu, and I read the implementation to confirm

Fixed documentation for cpu quota and period

---

src/cgroup.rs
src/error.rs
tests/cgroup.rs

Determine the cgroup mode in add_task() to avoid the wrong operation of the caller writing threads to cgroup.threads in non-thread mode.
Fixes: #103
Signed-off-by: yaoyinnan <yaoyinnan@foxmail.com>

Determine cgroup mode in add_task()

---

src/hugetlb.rs

With Cgroups v2, the file to use is "max", not "limit_in_bytes".
Fixes #112
Signed-off-by: Greg Kurz <groug@kaod.org>

Fix HugeTlbController::limit_in_bytes() for v2

---

src/devices.rs

The cgroup-rs should throw errors while setting devices cgroup if the rule is invalid. For example, if a cgroup has permissions of some devices. Then we set a `a *:* rwm` to its parent's `devices.deny`. An error should be thrown to make users realize that it is a invalid rule.

devices: Throw an error if device resources are invalid

---

src/cgroup.rs
src/devices.rs

The changes include:
- Expose `create()` and add `exists()` for `Cgroup`: The changes are allowed to load cgroup and test if the cgroup exists. If not exists, performing the `create()` directly to avoid performing `Cgroup::new()`.
- Make path of devices cgroup error more details: The origin path is either `devices.allow` or `devices.deny`. It not shows which cgroup it belongs to.

Minor changes for cgroup and devices subsystem

---

src/cgroup.rs

Adds a `.path()` method that allows the user to retrieve the path the cgroup is located at.

add .path() method

---

src/memory.rs

Kernel 5.19 introduces `memory.peak` and kernel 6.5 introduces `memory.swap.peak` to expose the memory and swap usage watermark. This change use these values to fill `max_usage_in_bytes`.

memory: use `peak` in `max_usage_in_bytes`

---

src/hierarchies.rs

I've been noticing an issue where creating a cgroup instance with an auto hierarchy fails and the error seems to come from: https://github.com/kata-containers/cgroups-rs/blob/8d29c194e38e5aed419384c07fd9ebf6ad39966c/src/cgroup.rs#L556-L560
.I believe this is because `cgroups-rs` thinks that the machine is using cgroup v2 where it isn't. This is happening at a customer site so I can't be sure 100% but we do compile all of our binaries with `musl` as the target as we want static builds. The system is an older aws endpoint with a 4.14 kernel so I'd assume it's using a hybrid cgroup (where systemd makes a fake unified cgroup but it's still cgroup v1 in reality) instead of a pure cgroup v2 system so that may be where the musl specific cgroupv2 check fails. I think we can avoid this musl …

make musl cgroupv2 identifying same as other target_envs

---

src/blkio.rs
src/cgroup.rs
src/cpu.rs
src/cpuacct.rs
src/cpuset.rs
src/devices.rs
src/freezer.rs
src/hierarchies.rs
src/hugetlb.rs
src/lib.rs
src/memory.rs
src/net_cls.rs
src/net_prio.rs
src/perf_event.rs
src/pid.rs
src/rdma.rs
src/systemd.rs

Correct path of cgroup when running a container in a container

---

src/cgroup.rs

In older kernel versions (tested with 5.10.208), the cgroup.controllers files ends with a newline. This newline is not trimmed and as such the application later can incorrectly consider that the last controller is not supported

controllers parsing is resilient to trailing newline

---

src/rdma.rs

Open rdma.max file and then read it.

rdma: read rdma.max file

---

src/hierarchies.rs

The documentation in the hierarchies module is outdated, this project does support cgroups2 and the unified hierarchy :)

hierarchies: Remove outdated documentation

---

src/lib.rs
src/manager/systemd.rs
src/systemd/cpu.rs
src/systemd/cpuset.rs
src/systemd/dbus/client.rs
src/systemd/dbus/error.rs
src/systemd/error.rs
src/systemd/mod.rs

The systemd version is purely informational and should not be parsed, as
documented in the [1]. In practice, systemd version has different formats
on OpenShift and Ubuntu.
This commit skips the version check and allows all operations. The errors
will be thrown from dbus when performing unsupported operations on obsolete
versions of systemd.
1: https://www.freedesktop.org/software/systemd/man/latest/org.freedesktop.systemd1.html

systemd: Do not check systemd version
